### ISSUE TITLE
waymark manager 0.9.0.0

### ISSUE THREAD

**Issue by AmenneHolelane** [PunishedPineapple/WaymarkPresetPlugin#1]
Describe the bug here:
clicking the json button in the /pwaymarks menu makes the plugin crash

Steps to reproduce the bug:
install waymark manager, type /pwaymarks, click the JSON button, see error message, close game, relaunch, repeat

Expected behavior
for it to not do that

**Comment by PunishedPineapple** [comment]
This was fixed in the [0.9.0.1 release](https://github.com/PunishedPineapple/WaymarkPresetPlugin/releases/tag/v0.9.0.1) (currently [PR'd](https://github.com/goatcorp/DalamudPlugins/pull/155) in the DalamudPlugins testing branch, so not available through /xlplugins until that gets accepted).

Unfortunately, you'll have to either manually remove any "null" entries in the Presets list in the plugin's config file.  Alternatively, if there's no data that you care about losing, just delete the plugin's config file altogether and start fresh.  I'm really sorry for the inconvenience; please let me know if you need more details about cleaning or deleting the config file.
