### ISSUE TITLE
hotkey to place first marker preset in list

### ISSUE THREAD

**Issue by muiem11** [PunishedPineapple/WaymarkPresetPlugin#12]
would it be possible to add a hotkey similar to /pwaymark to place the first marker preset for the current mapID?

**Comment by PunishedPineapple** [comment]
My initial thought is that I'd like to avoid doing this in order to keep things simple.

I guess before that, though, is there something about sticking the text command `/pwaymark place <#>` into a macro (along with `/pwaymark export` and/or the autoload presets from library option, if preferred), and putting that macro on a hotbar that doesn't work with your use case?

If you were to use the autoload option in the plugin, you'd only need a macro that does `/waymark preset 1` to accomplish this.

If you don't want to use that option, then I guess ya, you'd need a macro for each zone, which would get messy, so maybe I'm starting to see the problem.  I could add a text command to load the first X presets for a zone into the game, and then you could just have a single macro with both that command and the `/waymark preset 1`.  I'd rather maintain text commands than keybinds if possible.

**Comment by muiem11** [comment]
nice works like a charm. wasnt aware of those commands. thanks for the quick responds
