### ISSUE TITLE
[Request] Command to place waymark set via name

### ISSUE THREAD

**Issue by KhaozFrost** [PunishedPineapple/WaymarkPresetPlugin#13]
So firstly I took a look at this issue first to make sure of some things aswell as looking at the wiki front page and seen that in the description the plugin can technically place them directly. So I was in the middle of making some QOL bars and thought; hmmm. Wonder if you could load waymarks via command and have buttons within QOL to place them?  Well looking at the issue page below and importing a few to test I notice each waymark has a `Name:`

`{"Name":"Imported","MapID":759,"A":{"X":-0.188,"Y":75.0,"Z":-93.748,"ID":0,"Active":true},"B":{"X":18.887,"Y":75.0,"Z":-74.751,"ID":1,"Active":true},"C":{"X":-0.079,"Y":75.0,"Z":-55.359,"ID":2,"Active":true},"D":{"X":-19.088,"Y":75.0,"Z":-75.272,"ID":3,"Active":true},"One":{"X":0.184,"Y":75.0,"Z":-84.14,"ID":4,"Active":true},"Two":{"X":0.036,"Y":75.0,"Z":-78.772,"ID":5,"Active":true},"Three":{"X":-0.068,"Y":75.0,"Z":-71.663,"ID":6,"Active":true},"Four":{"X":-0.013,"Y":75.0,"Z":-65.432,"ID":7,"Active":true}}`

and was curious if it were at all possible to do something like /pwaymark set [name]

https://github.com/PunishedPineapple/WaymarkPresetPlugin/issues/12

oh and here is my QOL bar concept thus far:
https://prnt.sc/1k35tng

I planned on releasing it with some pre-configured waymarks once it was finished but want to see about this option first.

**Comment by PunishedPineapple** [comment]
Placing by name with a text command should be simple to add.  Just to clarify, when you say `/pwaymark set [name]`, is this just the example of a command to do that, or something additional?  There's already `/pwaymark place #`, so I'd just have it execute a search by name when the argument is non-numerical.

Anyway, I'll add this, but I'm mostly taking a break from FF14 right now, so it won't be immediately.  Sorry.

**Comment by KhaozFrost** [comment]
yeah its an example more or less based off like the example above it would be `/pwaymark set Imported` or so. I'm not certain how the pwaymark place # works I'm assuming its just based off the area or such? or does every waymark set have its own separate number?

**Comment by KhaozFrost** [comment]
oh, i see now what it does. yeah I'm thinking more: `so I'd just have it execute a search by name when the argument is non-numerical.`

**Comment by PunishedPineapple** [comment]
This has been added in [v1.3.1.0](https://github.com/PunishedPineapple/WaymarkPresetPlugin/releases/tag/v1.3.1.0).

Arguments to `/pwaymark place` enclosed in double quotes will now be searched by name instead of by index.  For example `/pwaymark place "e12s Full Uptime"` will try to find a preset with the name `e12s Full Uptime` and place it.  Case is ignored.

The new version of the plugin is for Dalamud API 4, so it will only work if you have testing enabled.  This will be available in the plugin installer on testing once [goatcorp/DalamudPlugins/pull/1134] is merged.

**Comment by KhaozFrost** [comment]
![image](https://user-images.githubusercontent.com/15788954/175752957-d684a3e1-8360-424b-9088-3bfb37dac2b3.png)

**Comment by KhaozFrost** [comment]
found the issue being odd to where if its not the correct zone it errors. makes sense actually but the place option via allows you to force place them so i was more confused by the unknown error message. resolved though ^^ 
(I loaded into normal to test instead of savage)

**Comment by KhaozFrost** [comment]
Would it be possible to add a command like /waymarks to open the vanilla waymarks menu via command? I seen you added the ability to attach the gui to the vanilla waymark menu so I might even just go that route with my qolbar instead of seperate buttons per instance.

**Comment by PunishedPineapple** [comment]
I did make a small change to how it locates the presets for the text command (while adding IPC for that).  I'll look into whether that was intentional or not, because honestly I cannot remember, and I frequently waffle back and forth on whether you should be able to place in zones other than the one for which the preset is saved.  Reopening until I get around to double checking that.

For the command to open the game's waymark window, the current best option was discussed in discord.  I *do* want a button (and/or text command, why not) to open the game's menu from the plugin (as well as an option have the main command (as the button) open the plugin), but it was out of my comfort zone to implement when I last looked into it.

**Comment by PunishedPineapple** [comment]
Ok, ya, it looks like I didn't set a flag that I should have for that text command.  Sorry!  It should be fixed for the next release.  That only really accounts for the `An unknown error occurred placing preset <number>` messages; I'm assuming that the others are from using wrong names, leaving off quotes, etc. to test, but if not, please let me know.

**Comment by PunishedPineapple** [comment]
Should be fixed in 1.4.3.0
