### ISSUE TITLE
Waymarks not always saving

### ISSUE THREAD

**Issue by spiral6** [PunishedPineapple/WaymarkPresetPlugin#16]
I've been using Waymarks on Endwalker Trial EX 1, and it hasn't been saving. It'll save the waymarks in the session, but as soon as I leave the session and/or exit the game/restart the game, it will not be saved and it won't be there the next time I instance in.

**Comment by PunishedPineapple** [comment]
Are you on version 1.3.1.2 of the plugin?  There was a bug where saving waymarks from the floor wouldn't always persist across restarts, but that got fixed a couple of days ago with that version.

**Comment by spiral6** [comment]
Yes, and I can confirm it's very inconsistent with saving waymarks still. I'm not certain if the data is just not being flushed correctly to wherever it's being saved or whatnot.

**Comment by PunishedPineapple** [comment]
I see.  I'm just calling `DalamudPluginInterface.SavePluginConfig` when a preset is added/changed/removed, and that doesn't give me back anything that I can verify.  Are you having issues with any other plugins not saving configuration?  File/folder permissions all correct for the plugin config directory?

If you can find a situation where you can consistently get it to happen with specific steps, let me know and I'll try to reproduce and look into it.  I'm honestly not sure what could be causing it in the current version, because the plugin is pretty simply just requesting that the configuration be saved when a preset is added/removed/changed.

First thing to check might be the filter on current zone checkbox in the library, since that saves the configuration every time you toggle it.  If the file isn't getting saved with that, it probably has to be something with your machine.

**Comment by spiral6** [comment]
I haven't had the issue since I started clicking `Filter on Current Zone` before and after I save the waymarks. 

I'm unable to reproduce the issue so I'll mark this as closed, but the above workaround may work if the issue happens again.

**Comment by PunishedPineapple** [comment]
Ideally you shouldn't have to do that; checking that box and seeing if it saved was more just to verify that the file was making it to disk every time reliably.  I can't be certain, but this issue sounds a lot like the previous version of the plugin got left around for some reason, but it thinks it's up to date.  Idk how that could happen with the normal plugin update process.  A couple things to check though (while the game isn't running):

1. Go to `%AppData%\XIVLauncher` on your computer, and verify that there are no versions of WaymarkPresetPlugin files in `devPlugins` or `testPlugins`.  If there are, just delete them.
2. In `installedPlugins`, go down in the WaymarkPresetPlugin folder until you find the .dll, right click it and select "Properties", then on the details tab, verify that it's at version 1.3.1.2.  If it's not, remove and reinstall the plugin from `/xlplugins` inside the game.  Your configuration and library don't get deleted when you remove a plugin, so you shouldn't have to worry about that, although if you're paranoid, the configuration is stored in the `pluginConfigs` folder in the location above, so you could copy it first as a backup.
