### ISSUE TITLE
Open on opening game's waymark

### ISSUE THREAD

**Issue by ArutanSipdrae** [PunishedPineapple/WaymarkPresetPlugin#17]
It would be nice to have a setting that either open the plugin on opening the game's waymark, or just replacing the game's waymark with the plugin at all

**Comment by PunishedPineapple** [comment]
I'll look into it again at some point when I next have to update the plugin.  I'm kind of hesitant to add more sigs/hooks since just more stuff to break, but we'll see.

In the meantime, if you don't mind having third party commands in your macros, I just have a macro with the following that I put on a hotbar to open it:
```
/micon "A" Waymark
/pwaymark
```

**Comment by PunishedPineapple** [comment]
There is now a pair of config options (as of v1.3.2.0) to address this.  One opens and closes the window with the game's waymark window, and another docks the plugin window to to the side of the game's waymark window.

Fully replacing the game's window is something that I would like to do at some point, but I do not possess the knowledge to make it work.
