### ISSUE TITLE
dpi scaling will be set 100% forced when load this plugin

### ISSUE THREAD

**Issue by FairyScript** [PunishedPineapple/WaymarkPresetPlugin#2]
Plugin version: 0.9.0.1

I have a UHD monitor, so i use borderless fullscreen and set the game dpi scaling to 150% to keep 60 fps. But when i load this plugi n, the game's scaling will change to 100%, looks like a 'borderless window'.

**Comment by PunishedPineapple** [comment]
I've tried this in various window modes, and with various ways of loading the plugin, but I've not been able to reproduce this,

There is one thing that comes to mind as a possiblity though; the call to getting part of the config file stuff looked to be at a strange spot in the game executable, but I ignored it because someone with more experience than me gave me the signature.  If you don't mind editing a line and recompiling, change line 78 in MemoryHandler.cs to `IntPtr pWaymarksLocation = mfpGetConfigSection.Invoke( IntPtr.Zero, 0x11 );`, rebuild, and give that plugin a try.  If you don't want to edit and rebuild it, let me know, and I can do it and send you a new dll.

**Comment by FairyScript** [comment]
@PunishedPineapple I tried to modify the code but not worked.

screenshot: 
![Snipaste_2020-07-31.png](https://i.loli.net/2020/07/25/beX8PVcRTG4gHJh.png)

Before load plugin: 
![20200725094318.png](https://i.loli.net/2020/07/25/VgLOJiFk3CYjp4D.png)

After:
![2020072509438.png](https://i.loli.net/2020/07/25/VLlscq4IXjZugpz.png)

**Comment by PunishedPineapple** [comment]
I see.  I misunderstood and thought that you meant the in-game UI scaling.  I don't explicitly do anything with window resolution or window size at all in this plugin, but I will try to see what I can find tomorrow.

The only thing that I can think of at all is that I do have a dependency to WPF to get the export to clipboard working (it was either that or WinForms, and I chose WPF since XL uses that already).

**Comment by PunishedPineapple** [comment]
I've still not been able to reproduce this with any combination of window mode and DPI scaling.  Here's a testing version of the plugin with all references to WPF removed, though, so if you can try this and let me know if it solves the issue for you, that would be helpful.

[WaymarkPresetPlugin_0.9.0.1_Testing.zip](https://github.com/PunishedPineapple/WaymarkPresetPlugin/files/4976958/WaymarkPresetPlugin_0.9.0.1_Testing.zip)

If you'd rather build yourself, changes were removing `PresentationCore` from the project's references, and removing `using System.Windows;` and the `Clipboard.SetText` call from lines 5 and 256 of `PluginUI.cs`, respectively.

**Comment by FairyScript** [comment]
It worked!

**Comment by PunishedPineapple** [comment]
Ok, I'll get something figured out to do the clipboard exports without that dependency.  Thank you for your help!

**Comment by PunishedPineapple** [comment]
This fix is now part of master in `/xlplugins`.  Sorry for the delay getting it out of testing, but I didn't want to push something into main right before 5.3 came out.
