### ISSUE TITLE
Impossible to delete

### ISSUE THREAD

**Issue by Valgrifer** [PunishedPineapple/WaymarkPresetPlugin#21]
![Animation](https://user-images.githubusercontent.com/13664715/165086286-0f977692-1de7-4df7-9f2a-3fde6c208c42.gif)
Impossible to delete, translate issue?

**Comment by PunishedPineapple** [comment]
This is probably due to your ImGui style having excessive spacing, so the confirmation button that appears below the delete button is getting cut off.  I changed the info pane window to automatically expand to fit the buttons instead of being a fixed size, but haven't made a release with that yet.  I'll try to finish up the other things that I was working on and see if I can get a release out Tuesday or Wednesday that fixes this.

**Comment by PunishedPineapple** [comment]
The layout issues that caused this should be fixed as of version 1.3.3.0.  Please let me know if you still have this problem after updating the plugin.

**Comment by Valgrifer** [comment]
Yes fixed, ty ^^
