### ISSUE TITLE
Request: Island Sanctuary Support

### ISSUE THREAD

**Issue by Noshei** [PunishedPineapple/WaymarkPresetPlugin#29]
So this plugin would be very useful for different gathering routes on the Island Sanctuary, unfortunately the saves done load at all, and the saved coordinates appear to not be correct.  It also flags the zone as Unknown Duty.

So getting this to work on the Island would be greatly appreciated.

**Comment by PunishedPineapple** [comment]
I'll take a look at it when I finally am able to get time to do the island quests, but if it's saving as `Unknown Duty`, it is probably not possible.  You might see if Gather Buddy works on the island, and if so, use its client-side gathering waymarks feature.


Long Version (if you care):

The game (and therefore this plugin, since it was created to mimic the waymark preset window at first) stores presets by "ContentFinderCondition", which is basically the instanced duty ID (everything in DF/RF, plus things like instanced quest duties).  Zones that don't have an associated ContentFinderCondition (like overworld zones, and probably in this case, your island) cannot have presets saved by the game because of this.  The plugin will save the waymarks, but since there's no valid zone ID, it gives them an ID of 0, which is listed as "Unknown Duty" in the plugin.

The plugin also uses the game's internal functions to place presets, which perform checks that saving/placing waymark presets is allowed in that zone, and that's not a check that is easily (or safely, imo) bypassed, so if the game's preset window doesn't allow you to save, chances are the plugin will not be able to place even if it could save them with a usable zone ID.

This brings us to client-side placement.  The plugin back end actually has had the ability to place client-side waymarks for quite some time, but it was never enabled because it was kinda always up in the air whether that was acceptable for a main repo plugin or not.  Gather Buddy added client-side waymarks for gathering points a few months ago, and I still kinda got no answer one way or the other whether they were acceptable in this plugin when I asked again then, so who knows.

**Comment by Noshei** [comment]
Thanks for the information, always nice to get details like this.

**Comment by PunishedPineapple** [comment]
I just checked, and ya, unfortunately the game's preset system won't allow the plugin to work on the island.  I'm going to look again into client side presets, but it won't be for a couple of weeks, which I know isn't that helpful for people grinding islands.  Sorry.

**Comment by PunishedPineapple** [comment]
This plugin has changed ownership, and I am no longer maintaining it.
