### ISSUE TITLE
Sort by name?

### ISSUE THREAD

**Issue by Farplaner** [PunishedPineapple/WaymarkPresetPlugin#3]
Right now the Waymark Library list is not sorted in any way that I can see, I think it would be much cleaner and easier to find the zone you want if it is sorted by name in alphabetical order.

**Comment by PunishedPineapple** [comment]
I'll think about it, but IMO, there's quite a bit to be said about leaving them sorted by the TerritoryType ID, which leaves them in roughly chronological order of content being added, keeping them in approximately the same order as they are listed in the Duty Finder.  I guess IDK for sure, but I would kind of expect most people that have played for a while to be used to that order of older duties being listed at the top progressing to the newest duties being listed at the bottom.

Sorting the presets themselves alphabetically was something that I planned to do, but then it was kind of obviated by grouping presets by zones and filtering by current zone leaving so few in the list that it wasn't worth the time.

Anyway, I'll leave this open to maybe add an option to sort zones/presets alphabetically, but it'd be low-priority, and I don't have the time to do anything for a while anyway.

**Comment by Farplaner** [comment]
Thanks, it makes a lot more sense now you have explained it.  I was thinking it was weird how the Alexander raids is mixed with the extremes in between, without realizing they're sorted by content release date.

In this case, I actually don't mind it sorting this way now.  If you don't feel like implementing an option for name sorting that's fine by me.

**Comment by karpik123** [comment]
I came to make an issue about it, but there's already one so I'll pitch in. This is my current order and it physically pains me to look at it:
![image](https://user-images.githubusercontent.com/33482843/163891896-7f87c0fb-c373-4bc2-b878-3f180e4b83a8.png)


Problems:
- no order to easily figure out if I have complete sets
- the list is getting long but my most commonly used items are at the bottom (if I didn't have font scaling 1.0 I'd have to scroll)
- Asphodelos order is absolute nonsense, while it is sorted by map id, SE didn't give them ids in sensible order in the first place

I understand that various people might want to group things in different way, by expansion, by difficulty, or simply just have most needed waymarks at the top. If someone wants to have it neat, they have to do the work to drag it once, which is arguably the same amount of work as configuring it in any other way.

IMO, the ability to drag and drop the order would be future proof. Since order could be handled outside of json with waymark information, it would also not break existing libraries? I'd be fine if backup export didn't preserve the order of the waymarks. It's already possible to drag and drop presets inside a zone, so drag and dropping zones wouldn't be awkward.

**Comment by PunishedPineapple** [comment]
While I don't personally feel sorting by the game's internal order is a big deal, especially when you can filter to only show the zone in which you currently are, I do see that it's annoyed a fair number of people since grouping by zone was added, so it is something that I plan to address.  I'd actually been looking into it a bit a month ago, but what I had didn't work quite right, so I scrapped it.  It's also only going to get worse as SE reworks old content and adds it to new TerritoryTypes, so like if you had markers for Titan normal (why? idk), it would now potentially be listed after p4s.

I do think that drag and drop reordering of zones is probably the best solution like you said, but I am going to think on it for a bit to make sure that I don't do something that I regret having to maintain in the future.  One of the big questions is that once you've dragged out of the default order, how do you add new entries to the list?  Do they just default to the end no matter what?  Do you try to insert them in a relevant place in the list?  Figuring out how to do the latter is probably quite difficult to get right.  Maybe it's best to just put anything not known in the sort data at the top, as it's presumably the most likely to be used.

Anyway, this is something that I plan to add after I get the help window stuff done.  There is some back-end work that probably has to be done first though, so don't expect anything for a month or so.

**Comment by karpik123** [comment]
I use filter by zone, but only when I'm using my library in the instance. My problem started elsewhere, I wanted to clear my waymarks after Pandemonium prog... and having well, 8 or more variants for each PxS, and wanting to tidy them up neatly in similarly named pairs, working on a scattered list was a pain. I don't think there's any functional problem to use waymarks when in the instance, but it has gotten more difficult to manage them 'outside' and this is where sorting comes in.

As to where to add newly added zones, for a moment I thought about adding it at the top, but I don't think it's a good idea. Import box is at the bottom, so for longer lists like mine (or smaller window size), you would add via import and it plops at the top, sounds pretty sad.

I would add new zones at the bottom of the existing order, this is where humans expect things to appear in most cases (and will work well with json import). I don't think there's any way you can reliably guess the best place to drop it. 

You can consider giving it some icon/colour/[ NEW ] mark for people to easily spot the new zone, but I don't think that's a big deal. I mean, when I was adding EW zones, it's not like I was completely lost when P4S appeared above Zodiark EX - skimming through the list did the trick. Until I read this issue, I was even unaware the sort order is quasi-chronological due to map ids, I assumed it's half-random or partially related to the order I added them in.

In terms of sorting, you can consider a setting that will override drag&drop, "Always sort zones in A-Z order". With this enabled, the plugin would not let people drag and drop anything. Then, you can reliably insert new zone into existing alphabetical order. A-Z sorting could work for lazy people who don't care enough to manually drag and drop zones in desired order, so it's quite tempting. A-Z and drag&drop are functionally mutually exclusive in my head, but it doesn't your plugin can't support both.

For me, the upside of drag and drop is that I'd be able to move EX trials from each expansions to be together, while also moving current content towards the top for my convenience. A-Z sorting won't let me do that, but A-Z order would solve current 'list isn't really in the most human friendly order' problem just the same.

**Comment by squidmade** [comment]
For finding the zone you want, one possibility would be a search box at the top where you can start typing the name of the zone and it will filter the list as you type. Although the original request was to allow sorting, the motivation behind the request seems to be about finding what you want.

As an intermediate step, another idea would be to allow pinning of specific zones which would then appear at the top of the list. That would at least solve the problem of being able to find the zones you care about (e.g. all the ones for the current tier). However to pin the zone you want you'd still need to visually find it in the list.

I'm looking to contribute so if either of these ideas sounds feasible/not a pain to maintain, I'd be up for giving it a shot.

**Comment by PunishedPineapple** [comment]
@karpik123 @Farplaner Out of curiosity, does what's shown in #23 address the usability issues that you've experienced, or do you still prefer something like drag and drop zone reordering?  It's ok either way; I was just getting ready to start looking at D&D during this maint, but with that, I'm not sure how I want to proceed.

**Comment by Farplaner** [comment]
Yes it does, for sure.  I'd love to see a search box that I can type in that filters the list on the fly.

**Comment by karpik123** [comment]
@PunishedPineapple #23 does not resolve my 'have a neat order to organise things' problem, two different cases.

#23 is useful for a couple cases when someone is not in the instance:
- "Oh crap, I going to do Endsinger EX, did I import any waymarks for it already?", you filter and you know
- Other example, I joined friends recently to farm mounts from older savages, I had to scan through the list to see if I have anything (I was checking multiple zones from diff expansions too, so it'd be much faster with filter if it was available then!). 
- It would also be handy when a friend asks "do you have any waymarks for X", if I'm not sure, I can quickly check using a filter

Filtering is the best way to find waymarks for specific zone (or low number of them) before you load into the instance, so it's a great addition, much more valuable than my ordering request!

However sorting/neat order is for more focused waymark library work, when you review and update all waymarks - especially if you're just starting organising them. Filtering is not helpful there, as you need to see all zones - preferred order of zones just makes the review easier and faster.

**Comment by PunishedPineapple** [comment]
Drag and drop reordering of zones, descending sorting of zones, and the search box from PR #23 are implemented as of version 1.4.1.0, which is available in `/xlplugins` when you have plugin testing enabled.  As usual, please back up your configuration before installing testing versions.

**Comment by PunishedPineapple** [comment]
Also, just a quick comment on the ideas mentioned above that were not implemented:
* Alphabetical ordering: With the way that the library data is currently structured, this is just too compulationally expensive on top of an already quite heavyweight plugin UI.  If I'm ever able to get around to fully encapsulating the library data so that sorting wouldn't be necessary every frame, I will revisit this.  (Laugh all you want at my poor design decisions; this plugin has balloned in scope substantially over the initial design).
* Pinned or preferred zones: Pinning would make the sort implementation more annoying, although it's not horrible if multiple people decide that they *really* want it.  Drag and dropping the desired zones at the top probably serves 90% of the same function, though.
* Grouping or sorting by other criteria (difficulty, etc.): I just don't feel that this is worth the significant additional complexity.
