### ISSUE TITLE
Plugin Adoption

### ISSUE THREAD

**Issue by squidmade** [PunishedPineapple/WaymarkPresetPlugin#36]
I submitted a PR to D17 to adopt this and Goat recommended I reach out. Would you be okay with me adopting this plugin? We can also chat via Discord DMs if you prefer.

**Comment by PunishedPineapple** [comment]
If you feel up to maintaining/owning the code nightmare I created, go for it.  You had PR'd the double click placement thing, so I guess you basically know what you'd be getting into as far as it not being structured the same as most people's plugins.  I can try to answer questions via DM if needed.  Beware the map loading stuff if you ever work on that; it can have some gotchas because of having to thread the file loading, as well as the sub-map paths being a bit awkward to get out of the sheets.

**Comment by squidmade** [comment]
Thanks, I appreciate you offering to answer questions! I'll let you know if I have any.

**Comment by squidmade** [comment]
I sent a friend request on Discord so we can DM. I'd like to avoid posting my tag, but if you'd like to confirm you should be able to find me if you search conversations for squidmade

**Comment by PunishedPineapple** [comment]
It appears that everything has been taken care of.  This repo will be archived shortly.
